name: gleap
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Google
  google_maps_flutter: ^0.5.16
  firebase_core: ^0.4.0+5
  firebase_auth: ^0.11.1+6
  cloud_firestore: ^0.12.5+1
  firebase_storage: ^3.0.1
  shared_preferences: ^0.5.3+1
  url_launcher: ^5.0.3
  image_picker: ^0.6.0+9

  flutter_secure_storage: ^3.2.1+1
  rxdart: ^0.22.0
  http: ^0.12.0+2
  json_annotation: ^2.4.0
  flutter_i18n: ^0.6.3
  cached_network_image: ^0.8.0
  sqflite: ^1.1.5
  mime: ^0.9.6+3
  percent_indicator: ^2.1.0
  country_icons: ^1.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sensors: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  json_serializable: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/locales/en.json    # Locale
    - assets/locales/fi.json    # Locale
    #- assets/v2/Cell Metabolism/btn_blank.jpg
    #- assets/v2/Cell Metabolism/btn_blank_info.png
    #- assets/v2/Cell Metabolism/btn_hiit.png
    #- assets/v2/Cell Metabolism/btn_see_how_your_friends_are_doing.png
    #- assets/v2/Cell Metabolism/btn_x2.jpg
    #- assets/v2/Cell Metabolism/btn_x4.jpg
    #- assets/v2/Cell Metabolism/burning_icon.png
    #- assets/v2/Cell Metabolism/cell_metabolism_today_graph_v3.png
    #- assets/v2/Cell Metabolism/icon_done_off.png
    #- assets/v2/Cell Metabolism/icon_done_on.png
    #- assets/v2/Cell Metabolism/icon_x_axis.png
    #- assets/v2/Cell Metabolism/icon_y_axis.png
    #- assets/v2/Cell Metabolism/icon_z_axis.png
    #- assets/v2/Cell Metabolism/me_and_other_users_new.png
    #- assets/v2/Cell Metabolism/me_and_other_users_v3.png
    #- assets/v2/Cell Metabolism/morning_boost.png
    #- assets/v2/Cell Metabolism/nutrition.png
    #- assets/v2/Contact/bg_contact_global.jpg
    #- assets/v2/Frontpage/bg_3dsensors.png
    #- assets/v2/Frontpage/bg_cellmetabolism.png
    #- assets/v2/Frontpage/bg_challenges.png
    #- assets/v2/Frontpage/bg_premium.png
    #- assets/v2/Frontpage/bg_hiit.png
    #- assets/v2/Frontpage/bg_molecules.png
    #- assets/v2/Frontpage/bg_morningboost.png
    #- assets/v2/Frontpage/bg_myworld.png
    #- assets/v2/Frontpage/bg_science.png
    #- assets/v2/Frontpage/bg_story_and_origin.png
    #- assets/v2/Frontpage/logo_GLEAP.png
    #- assets/v2/HIIT/workout_1.png
    #- assets/v2/HIIT/workout_2.png
    #- assets/v2/HIIT/workout_3.png
    #- assets/v2/Login/Welcome_1080x2244.jpg
    #- assets/v2/Menu/xhdpi_48x48_menu_faq.png
    #- assets/v2/Menu/xhdpi_48x48_menu_invite_friends.png
    #- assets/v2/Menu/xhdpi_48x48_menu_molecules.png
    #- assets/v2/Menu/xhdpi_48x48_menu_my_profile.png
    #- assets/v2/Menu/xhdpi_48x48_menu_my_rewards.png
    #- assets/v2/Menu/xhdpi_48x48_menu_my_world.png
    #- assets/v2/Menu/xhdpi_48x48_menu_nutritional_reminder.png
    #- assets/v2/Menu/xhdpi_48x48_menu_premium.png
    #- assets/v2/Menu/xhdpi_48x48_menu_sensors.png
    #- assets/v2/Menu/xhdpi_48x48_menu_shop.png
    #- assets/v2/Menu/xhdpi_48x48_menu_team_challenges.png
    #- assets/v2/My Body Functions/bg_1_intro_narrow.jpg
    #- assets/v2/My Body Functions/bg_2_cellmetabolism_narrow.jpg
    #- assets/v2/My Body Functions/bg_3_molecule_narrow.jpg
    #- assets/v2/Cell Metabolism/icon_molecule.png
    #- assets/v2/Cell Metabolism/icon_360degrees.png
    #- assets/v2/Cell Metabolism/icon_cellmetabolism.png
    #- assets/v2/My World/bg_myworld.jpg
    #- assets/v2/My World/btn_myac.png
    #- assets/v2/My World/country_list.png
    #- assets/v2/My World/logo_my_world.png
    #- assets/v2/MyAC/bg_myworld_myac.jpg
    #- assets/v2/MyAC/logo_myac.png
    #- assets/v2/Profile/bg_profile.jpg
    #- assets/v2/Profile/profile_activity_lvl_1.png
    #- assets/v2/Profile/profile_activity_lvl_2.png
    #- assets/v2/Profile/profile_activity_lvl_3.png
    #- assets/v2/Profile/profile_activity_lvl_4.png
    #- assets/v2/Profile/profile_DoB.png
    #- assets/v2/Profile/profile_gender.png
    #- assets/v2/Profile/profile_height.png
    #- assets/v2/Profile/profile_img.jpg
    #- assets/v2/Profile/profile_record_1.png
    #- assets/v2/Profile/profile_record_2.png
    #- assets/v2/Profile/profile_record_3.png
    #- assets/v2/Profile/profile_record_4.png
    #- assets/v2/Profile/profile_weight.png

    - assets/v3/3D_Sensors/bg_1_intro_narrow.jpg
    - assets/v3/3D_Sensors/bg_2_cellmetabolism_narrow.jpg
    - assets/v3/3D_Sensors/bg_3_molecule_narrow.jpg
    - assets/v3/3D_Sensors/bg_x_value.png
    - assets/v3/3D_Sensors/bg_y_value.png
    - assets/v3/3D_Sensors/bg_z_value.png
    - assets/v3/3D_Sensors/icon_360degrees.png
    - assets/v3/3D_Sensors/icon_cellmetabolism.png
    - assets/v3/3D_Sensors/icon_molecule.png
    - assets/v3/3D_Sensors/icon_x_axis.png
    - assets/v3/3D_Sensors/icon_y_axis.png
    - assets/v3/3D_Sensors/icon_z_axis.png
    - assets/v3/Cell_Metabolism/btn_blank.jpg
    - assets/v3/Cell_Metabolism/btn_blank_info.png
    - assets/v3/Cell_Metabolism/btn_hiit.png
    - assets/v3/Cell_Metabolism/btn_see_how_your_friends_are_doing.png
    - assets/v3/Cell_Metabolism/btn_x2.jpg
    - assets/v3/Cell_Metabolism/btn_x4.jpg
    - assets/v3/Cell_Metabolism/burning_icon.png
    - assets/v3/Cell_Metabolism/icon_x_axis.png
    - assets/v3/Cell_Metabolism/icon_y_axis.png
    - assets/v3/Cell_Metabolism/icon_z_axis.png
    - assets/v3/Cell_Metabolism/morning_boost.png
    - assets/v3/Cell_Metabolism/nutrition.png
    - assets/v3/Contact/bg_contact_global.jpg
    - assets/v3/Frontpage/bg_3dsensors.png
    - assets/v3/Frontpage/bg_3dsensors.png
    - assets/v3/Frontpage/bg_cellmetabolism.png
    - assets/v3/Frontpage/bg_challenges.png
    - assets/v3/Frontpage/bg_hiit.png
    - assets/v3/Frontpage/bg_molecules.png
    - assets/v3/Frontpage/bg_morningboost.png
    - assets/v3/Frontpage/bg_myworld.png
    - assets/v3/Frontpage/bg_premium.png
    - assets/v3/Frontpage/bg_science.png
    - assets/v3/Frontpage/bg_story_and_origin.png
    - assets/v3/Frontpage/logo_GLEAP.png
    - assets/v3/HIIT/workout_1.png
    - assets/v3/HIIT/workout_2.png
    - assets/v3/HIIT/workout_3.png
    - assets/v3/Login/bg_login.jpg
    - assets/v3/Login/bg_login_blank.jpg
    - assets/v3/Menu/xhdpi_48x48_menu_molecules.png
    - assets/v3/Menu/xhdpi_48x48_menu_my_rewards.png
    - assets/v3/Menu/xhdpi_48x48_menu_my_world.png
    - assets/v3/Menu/xhdpi_48x48_menu_premium.png
    - assets/v3/Menu/xhdpi_48x48_menu_sensors.png
    - assets/v3/Menu/xhdpi_48x48_menu_team_challenges.png
    - assets/v3/My_World/bg_myworld.jpg
    - assets/v3/My_World/bg_myworld_myac.jpg
    - assets/v3/My_World/btn_myac.png
    - assets/v3/My_World/country_list.png
    - assets/v3/My_World/logo_myac.png
    - assets/v3/My_World/logo_my_world.png
    - assets/v3/Profile/bg_profile.jpg



  fonts:
    - family: HelveticaLTStd
      fonts:
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Blk.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-BlkCond.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-BlkCondObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-BlkObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Bold.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-BoldCond.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-BoldCondObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-BoldObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Comp.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Cond.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-CondObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-ExtraComp.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Light.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-LightCond.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-LightCondObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-LightObl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Obl.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-Roman.otf
        - asset: assets/fonts/HelveticaLTStd/HelveticaLTStd-UltraComp.otf
    - family: Corbel
      fonts:
      - asset: assets/fonts/Corbel/corbel.ttf
      - asset: assets/fonts/Corbel/corbelb.ttf
      - asset: assets/fonts/Corbel/corbeli.ttf
      - asset: assets/fonts/Corbel/corbelz.ttf
      - asset: assets/fonts/Corbel/corbel_0.ttf
      - asset: assets/fonts/Corbel/corbelb_0.ttf
      - asset: assets/fonts/Corbel/corbeli_0.ttf
      - asset: assets/fonts/Corbel/corbelz_0.ttf
